### ISSUE TITLE
Síntesis "Buenas Prácticas en Gestión de Proyectos"

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/sintesis-Anthony4523#2]
[Síntesis_Buenas prácticas en Gestión de Proyectos.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Anthony4523/files/7150045/Sintesis_Buenas.practicas.en.Gestion.de.Proyectos.pdf)

**Comment by JeserLeonel** [comment]
**Calificación = 20 ** Excelente.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
